### ISSUE TITLE
安卓demo运行报错：错误: -source 1.7 中不支持类型注释     Contact sales@agora.io and get Faceunity auth file

### ISSUE THREAD

**Issue by SongJeen** [AgoraIO-Usecase/AgoraLive#15]
安卓demo运行报错，编译不通过：错误: -source 1.7 中不支持类型注释     Contact sales@agora.io and get Faceunity auth file
http://chuantu.xyz/t6/739/1594628867x-633054266.png

**Comment by yoreland** [comment]
authpack 是您从相芯处申请的证书，项目代码里不包含

**Comment by SongJeen** [comment]
相芯这个证书可以不用吗？

**Comment by brianxcli** [comment]
可以的，不过美颜和虚拟主播不可用。另外需要删减些和美颜相关的代码。
