### ISSUE TITLE
项目运行不起来

### ISSUE THREAD

**Issue by gucuncun** [AgoraIO-Usecase/AgoraLive#16]
项目安装上去  faceunity库代码直接报红  根本运行不起来

**Comment by CavanSu** [comment]
你运行的是哪个分支？ 我刚刚把开发分支合回 master 你试试看

**Comment by ZhangBingbin** [comment]
faceunity库似乎有问题

**Comment by ZhangBingbin** [comment]
AgoraLive-Android master分支

**Comment by CavanSu** [comment]
有具体的报错吗？能否上传一下截图 @ZhangBingbin

**Comment by wzs0316lei** [comment]
faceunity这个依赖包缺少wrapper包，
例子---如下
import static com.faceunity.wrapper.faceunity.FU_ADM_FLAG_FLIP_X;
import static com.faceunity.wrapper.faceunity.fuItemSetParam;
import com.faceunity.wrapper.faceunity;

依赖找不到，也就是说faceunity不完整

**Comment by ZhangBingbin** [comment]
<img width="895" alt="WX20200721-134238@2x" src="https://user-images.githubusercontent.com/16457177/88017390-249c3900-cb58-11ea-8c49-a0dfedd7c246.png">

**Comment by ZhangBingbin** [comment]
<img width="1393" alt="WX20200721-134414@2x" src="https://user-images.githubusercontent.com/16457177/88017465-48f81580-cb58-11ea-8423-3b8253c6e346.png">

**Comment by OvenCroc** [comment]
我也是这样 大佬解决了没得?

**Comment by plutoless** [comment]
@ZhangBingbin 这是faceunity的证书文件，需要您找销售要一下

**Comment by brianxcli** [comment]
更新了代码，没有相芯授权的时候允许编译，但美颜和虚拟主播不可用。
