### ISSUE TITLE
Android版本无法编译

### ISSUE THREAD

**Issue by MarcoZhan** [AgoraIO-Usecase/AgoraLive#23]
1、authpack类无法编译
![11](https://user-images.githubusercontent.com/17327129/88126230-ad23e380-cc03-11ea-9093-4594b2ab5bc5.png)

2、com.faceunity.wrapper包找不到，Library内缺失
![11](https://user-images.githubusercontent.com/17327129/88126498-376c4780-cc04-11ea-8a69-cb0cd0939ef7.png)
![11](https://user-images.githubusercontent.com/17327129/88126521-44893680-cc04-11ea-8d51-542ca7061151.png)

**Comment by shaobin204** [comment]
+1,我下载下来运行，也遇到同样的情况

**Comment by hao321** [comment]
+1,我下载下来运行，也遇到同样的情况

**Comment by plutoless** [comment]
有库依赖问题的，请确认阅读readme后下载了依赖的sdk包并放到了指定的位置
authpack有问题的，需要联系销售要一下faceunity的证书并替换到指定位置，我们正在处理这块，确保faceunity证书不提供应用也可以正常运行，只是美颜不工作

**Comment by brianxcli** [comment]
更新了代码，没有相芯授权的时候允许编译，但美颜和虚拟主播不可用。
