### ISSUE TITLE
最新版android demo还是跑不通，你们更新前能不能自己跑通一下？？

### ISSUE THREAD

**Issue by SongJeen** [AgoraIO-Usecase/AgoraLive#27]
FURenderer里面少了com.faceunity.wrapper.faceunity，报错：
错误: 程序包com.faceunity.wrapper不存在import com.faceunity.wrapper.faceunity;
                            ^

**Comment by brianxcli** [comment]
请你拷贝一下faceunity的jar包到工程里

**Comment by 15104422827** [comment]
faceunity的jar 哪里有

**Comment by 15104422827** [comment]
> FURenderer里面少了com.faceunity.wrapper.faceunity，报错：
> 错误: 程序包com.faceunity.wrapper不存在import com.faceunity.wrapper.faceunity;
> ^

https://download.agora.io/components/release/Faceunity-Android-v6.4.zip
看READ.ME

**Comment by plutoless** [comment]
应该解决了
