### ISSUE TITLE
What is RTMP URL from where i can get it?

### ISSUE THREAD

**Issue by DkKhan786** [AgoraIO-Usecase/AgoraLive#30]
PK-Host Repo : https://github.com/AgoraIO-Usecase/Online-PK

from where i can get these URL i didn't see any thing this my Agora Dashboard.
and please if there any proper documentation or Implementation guide how to implement PK-Host the URL you defined in Guide it's working 404 error. 

```
public final static String PUBLISH_URL = <##YOUR PUBLISH RTMP URL##>;
public final static String PUBLISH_PULL_URL = <##YOUR PLAY RTMP URL##>;
```

**Comment by plutoless** [comment]
@DkKhan786 you will need to provide this URL yourself. You can obtain rtmp url from youtube or whatever service provider who provides this.

**Comment by plutoless** [comment]
closed as not relevant to this repo.
