### ISSUE TITLE
package com.faceunity.wrapper does not exist

### ISSUE THREAD

**Issue by ohari5336** [AgoraIO-Usecase/AgoraLive#33]
`C:\Users\Hari OM\Desktop\AgoraLive-Android\faceunity\src\main\java\com\faceunity\FURenderer.java:26: error: package com.faceunity.wrapper does not exist
import com.faceunity.wrapper.faceunity;
                            ^`

![image](https://user-images.githubusercontent.com/22674877/98636443-def4bd80-234c-11eb-9ca5-11ef320f1a74.png)

**Comment by brianxcli** [comment]
Please take a look at the readme file supported for each platform. It shows steps how to build the project.

**Comment by jalal-hassane** [comment]
Hello guys,
I've done the steps from readme file (except for getting faceunity license which I think is not related to this error) but still facing the same problem:
error: package com.faceunity.wrapper does not exist
please help

**Comment by vishnutejar** [comment]
i am also facing same issues.

**Comment by brianxcli** [comment]
faceunity sdk is not provided in the project, you are charged for the licence

> i am also facing same issues.
