### ISSUE TITLE
项目一直在编译

### ISSUE THREAD

**Issue by nanxunwanfeng** [AgoraIO-Usecase/AgoraLive#37]
down zip包打开项目一直在编译，as直接拉也是

**Comment by tanfangliang** [comment]
mavenCentral()
 maven { url 'https://maven.google.com' }试试呢。

**Comment by Hyingqi** [comment]
为什么项目一直在编译中，好几个小时都这样，还有为什么不把项目放到阿里的镜像仓库中，你拿放在google中编老半天都不能成功

**Comment by Hyingqi** [comment]
> mavenCentral()
> maven { url 'https://maven.google.com' }试试呢。

试过不行

**Comment by brianxcli** [comment]
为国际用户使用的，不能直接配置国内的镜像，有需要的请自行设置
