### ISSUE TITLE
missing com.faceunity.wrapper

### ISSUE THREAD

**Issue by csuguoyq** [AgoraIO-Usecase/AgoraLive#39]
C:\androiddemo\AgoraLive-master\AgoraLive-Android\faceunity\src\main\java\com\faceunity\FURenderer.java:26: 错误: 程序包com.faceunity.wrapper不存在
import com.faceunity.wrapper.faceunity;

**Comment by plutoless** [comment]
这边需要参考一下readme放一下依赖库
