### ISSUE TITLE
faceunity error in Android Studio

### ISSUE THREAD

**Issue by wann2** [AgoraIO-Usecase/AgoraLive#41]
I'd like to test AgoraLive at android phone.
When I open the sources to build, I got the below error.
Do I have to need to change some config file? How can I fix it?
I use classpath 'com.android.tools.build:gradle:4.2.2' in build.gradle.

<img width="1246" alt="스크린샷 2021-07-06 오후 7 46 00" src="https://user-images.githubusercontent.com/8732515/124587983-3a069200-de93-11eb-9ff3-44926f9e3018.png">

**Comment by brianxcli** [comment]
please see readme file and find instructions for installing necessary libraries
